spring.datasource.url=jdbc:mysql://localhost:4000/tpfoyer
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#dima testa3ml port
#kif tra execution hakaka ma3natha raw ye5dem wjawo behi
#fil spring boot creation de chaque entitie automatique a traver annotation @entity hu